#!/bin/env python
import os
header='''\
#!/bin/bash
'''
aaa=''
ic=0
ijob=open("jobque",'r').read().split('\n')
for ix in ijob:
    ic=ic+1
    #aaa=aaa+ix
    aaa= aaa+ 'if [ $1 == '+ '%i' % ic +' ]; then\n' + ix+ '\n'+'fi\n'
jobf="test.sh"
f=open(jobf,'w')
f.write(header+'\n'+aaa+'\n')
f.close()
#os.system('pjsub '+jobf)
